version: '3.8'

services:
  backend:
    build: .
    container_name: dashboard_backend_dev
    ports:
      - "3000:3000"
    volumes:
      # Persistent database volume
      - ./data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=development
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
